language: python
python:
# 2.5 is for centos and the old cranky people 
#  - "2.5"
#  - "2.6"
  - "2.7"
#  - "3.3"
#  not available in travis 
install:
  - pip install . 
script:
 - python setup develop
 
